import ExcelJS from "exceljs";
import { writeFile } from "fs/promises";

const preparedPatients = [
  {
    order: 1,
    idReferral: 355525,
    ihalatyReference: "32098021",
    adherentId: "41136914",
    adherentName: " hamam  shehry",
    adherentNationalId: "1152293344",
    referralDate: "2025-09-01T15:30:48",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 2,
    idReferral: 355493,
    ihalatyReference: "32096743",
    adherentId: "41135436",
    adherentName: " JWAHER ALDGASH",
    adherentNationalId: "1117648459",
    referralDate: "2025-09-01T12:40:44",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 3,
    idReferral: 355485,
    ihalatyReference: "32092709",
    adherentId: "38473639",
    adherentName: " mazigha  saleh",
    adherentNationalId: "1058151778",
    referralDate: "2025-09-01T12:07:00",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 4,
    idReferral: 355446,
    ihalatyReference: "32096119",
    adherentId: "40666231",
    adherentName: " ALI,AHMED -",
    adherentNationalId: "1024919159",
    referralDate: "2025-09-01T08:08:15",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 5,
    idReferral: 355418,
    ihalatyReference: "32095894",
    adherentId: "41133202",
    adherentName: " عبدالله  الاحمري",
    adherentNationalId: "1011302302",
    referralDate: "2025-08-31T23:36:04",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 6,
    idReferral: 355412,
    ihalatyReference: "32095587",
    adherentId: "41132425",
    adherentName: " shahrah  Alqahtani",
    adherentNationalId: "1021050016",
    referralDate: "2025-08-31T21:31:55",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 7,
    idReferral: 355411,
    ihalatyReference: "32092056",
    adherentId: "41132420",
    adherentName: " YAHYA  ASIRI",
    adherentNationalId: "1016201244",
    referralDate: "2025-08-31T21:29:48",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 8,
    idReferral: 355407,
    ihalatyReference: "32095808",
    adherentId: "41132195",
    adherentName: " Ashwaq  Alahmari",
    adherentNationalId: "1084252210",
    referralDate: "2025-08-31T21:03:31",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 9,
    idReferral: 355396,
    ihalatyReference: "32095612",
    adherentId: "41130822",
    adherentName: " ALANOOD  ASIRI",
    adherentNationalId: "1097100604",
    referralDate: "2025-08-31T17:47:37",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 10,
    idReferral: 355390,
    ihalatyReference: "32095377",
    adherentId: "36738638",
    adherentName: " YASSER MAHDI",
    adherentNationalId: "1007251299",
    referralDate: "2025-08-31T16:50:09",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 11,
    idReferral: 355370,
    ihalatyReference: "32093946",
    adherentId: "41122273",
    adherentName: " ABDULLAH  FARWAN",
    adherentNationalId: "1212859340",
    referralDate: "2025-08-31T12:13:51",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 12,
    idReferral: 355279,
    ihalatyReference: "32092840",
    adherentId: "41116778",
    adherentName: " MASTOURAH ALSHAHRANI",
    adherentNationalId: "1054573777",
    referralDate: "2025-08-30T08:21:12",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 13,
    idReferral: 355270,
    ihalatyReference: "32092697",
    adherentId: "41116626",
    adherentName: " SULTAN  ALQAHTANI",
    adherentNationalId: "1081490169",
    referralDate: "2025-08-30T04:06:05",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 14,
    idReferral: 355235,
    ihalatyReference: "32092264",
    adherentId: "41112543",
    adherentName: " NORA AL FATEEH",
    adherentNationalId: "1188670051",
    referralDate: "2025-08-29T15:15:03",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 15,
    idReferral: 355231,
    ihalatyReference: "32091340",
    adherentId: "41114559",
    adherentName: " FATIMAH ALSHAHRANI",
    adherentNationalId: "1004608996",
    referralDate: "2025-08-29T14:04:12",
    referralType: "Emergency",
    referralReason: "Health Crisis",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "discharged",
    paid: 0,
  },
  {
    order: 16,
    idReferral: 355226,
    ihalatyReference: "32092407",
    adherentId: "41114524",
    adherentName: " HALIMAH  ALQAHTANI",
    adherentNationalId: "1054547144",
    referralDate: "2025-08-29T13:13:33",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 17,
    idReferral: 355224,
    ihalatyReference: "32092395",
    adherentId: "41114441",
    adherentName: " MALAK ALSHMRANI",
    adherentNationalId: "1213953555",
    referralDate: "2025-08-29T11:44:28",
    referralType: "Emergency",
    referralReason: "Health Crisis",
    sourceZone: "Bisha",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 18,
    idReferral: 355195,
    ihalatyReference: "32092047",
    adherentId: "41113642",
    adherentName: " ALANOUD  ASIRI",
    adherentNationalId: "1219419379",
    referralDate: "2025-08-28T23:49:33",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 19,
    idReferral: 355194,
    ihalatyReference: "32092057",
    adherentId: "29364554",
    adherentName: " Saeed Al Ahmary",
    adherentNationalId: "1064056458",
    referralDate: "2025-08-28T23:41:35",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 20,
    idReferral: 355189,
    ihalatyReference: "32091776",
    adherentId: "41113262",
    adherentName: " JABER  ALTALIDI",
    adherentNationalId: "1205950130",
    referralDate: "2025-08-28T22:18:00",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 21,
    idReferral: 355175,
    ihalatyReference: "32091715",
    adherentId: "32689227",
    adherentName: " Ali AlHiyah",
    adherentNationalId: "1049918178",
    referralDate: "2025-08-28T19:56:39",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 22,
    idReferral: 355138,
    ihalatyReference: "32089493",
    adherentId: "41109299",
    adherentName: " HAMZAH  ALSHEHRI",
    adherentNationalId: "1030081846",
    referralDate: "2025-08-28T12:13:40",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 23,
    idReferral: 355118,
    ihalatyReference: "32089346",
    adherentId: "41107535",
    adherentName: " NORAH ALESSA",
    adherentNationalId: "1045199344",
    referralDate: "2025-08-28T01:29:45",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 24,
    idReferral: 355092,
    ihalatyReference: "32088411",
    adherentId: "40504063",
    adherentName: " MOEIDA ASIRI",
    adherentNationalId: "1048248007",
    referralDate: "2025-08-27T15:03:53",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 25,
    idReferral: 355085,
    ihalatyReference: "32086841",
    adherentId: "41103800",
    adherentName: " KHAMIS  ALZUBAIDI",
    adherentNationalId: "1131817841",
    referralDate: "2025-08-27T14:02:25",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 26,
    idReferral: 355080,
    ihalatyReference: "32081921",
    adherentId: "36122450",
    adherentName: " Saleha Alshehri",
    adherentNationalId: "1061643118",
    referralDate: "2025-08-27T12:53:08",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 27,
    idReferral: 355048,
    ihalatyReference: "32086514",
    adherentId: "31766850",
    adherentName: " FATMAH MOHAMED MAHLAWI",
    adherentNationalId: "1060623590",
    referralDate: "2025-08-26T21:51:43",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 28,
    idReferral: 355046,
    ihalatyReference: "32086175",
    adherentId: "41099940",
    adherentName: " SALEM  ALQAHTANI",
    adherentNationalId: "1042839504",
    referralDate: "2025-08-26T21:42:43",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 29,
    idReferral: 355043,
    ihalatyReference: "32086194",
    adherentId: "41099836",
    adherentName: " ALHASSAN  MUTMI",
    adherentNationalId: "1087341267",
    referralDate: "2025-08-26T21:27:09",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 30,
    idReferral: 355041,
    ihalatyReference: "32086190",
    adherentId: "41099645",
    adherentName: " AMER  ALASIRI",
    adherentNationalId: "1091177509",
    referralDate: "2025-08-26T21:02:18",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 31,
    idReferral: 355019,
    ihalatyReference: "32083765",
    adherentId: "41096981",
    adherentName: " نوف  الاسمري",
    adherentNationalId: "1020955082",
    referralDate: "2025-08-26T14:47:37",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 32,
    idReferral: 355016,
    ihalatyReference: "32082235",
    adherentId: "31829949",
    adherentName: " AZIZAH ALOADAY",
    adherentNationalId: "1060319983",
    referralDate: "2025-08-26T14:16:47",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 33,
    idReferral: 355001,
    ihalatyReference: "32079385",
    adherentId: "41095371",
    adherentName: " IBRAHIM  ALKAYYADI",
    adherentNationalId: "1070735103",
    referralDate: "2025-08-26T11:37:35",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 34,
    idReferral: 354987,
    ihalatyReference: "32081256",
    adherentId: "41094172",
    adherentName: " TALAL  ALSHADIDI",
    adherentNationalId: "1141330736",
    referralDate: "2025-08-26T08:30:58",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 35,
    idReferral: 354984,
    ihalatyReference: "32084193",
    adherentId: "41094132",
    adherentName: " SAEED  ALSHAHRANI",
    adherentNationalId: "1063399743",
    referralDate: "2025-08-26T08:03:10",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 36,
    idReferral: 354959,
    ihalatyReference: "32084000",
    adherentId: "41093054",
    adherentName: " SHAIKHAH  ALQAHTANI",
    adherentNationalId: "1005473796",
    referralDate: "2025-08-25T22:41:29",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "admitted",
    paid: 0,
  },
  {
    order: 37,
    idReferral: 354955,
    ihalatyReference: "32083798",
    adherentId: "41092633",
    adherentName: " RAJHAA  ALASMARI",
    adherentNationalId: "1025681741",
    referralDate: "2025-08-25T21:42:16",
    referralType: "Emergency",
    referralReason: "Bed Unavailable",
    sourceZone: "Asir",
    sourceProvider: "",
    assignedProvider: "TADAWI MEDICALhospital- khamis Mushayt",
    disease: "",
    status: null,
    tabName: "discharged",
    paid: 0,
  },
];

const excelColumns = [
  { header: "order", key: "order", width: 12 },
  { header: "Referral Date", key: "referralDate", width: 24 },
  { header: "GMS Referral Id", key: "idReferral", width: 20 },
  { header: "MOH Referral Nb", key: "ihalatyReference", width: 20 },
  { header: "Patient Name", key: "adherentName", width: 37 },
  { header: "National ID", key: "adherentNationalId", width: 20 },
  { header: "Referral Type", key: "referralType", width: 20 },
  { header: "Referral Reason", key: "referralReason", width: 28 },
  { header: "Source Zone", key: "sourceZone", width: 15 },
  { header: "Assigned Provider", key: "assignedProvider", width: 52 },
];

(async () => {
  const fileTitle = "from-25_08_2025-to-01_09_2025";
  const fullFileTitle = `admitted-${fileTitle}`;

  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet(fileTitle);
  sheet.columns = excelColumns;

  preparedPatients.forEach((row) => sheet.addRow(row));

  sheet.getRow(1).eachCell((cell) => {
    cell.font = {
      name: "Arial",
      size: 14,
      bold: true,
    };
    cell.alignment = {
      horizontal: "center",
      vertical: "middle", // optional, to center vertically too
    };
  });

  sheet.eachRow((row) => {
    row.eachCell((cell) => {
      cell.font = {
        name: "Arial",
        size: 12,
        bold: false,
      };
      cell.alignment = {
        horizontal: "center",
        vertical: "middle", // optional, to center vertically too
      };
    });
  });

  const buffer = await workbook.xlsx.writeBuffer();

  await writeFile(
    `D:/work/future/clone-icare/automize-icare/results/summary/${fullFileTitle}.xlsx`,
    buffer
  );
})();
